### PR TITLE
Node 10 version

### PR DESCRIPTION
**Pull request by samjeffress**
update iltorb to iltorb-v2.4.3-node-v64-linux-x64.tar.gz from https://github.com/MayhemYDG/iltorb/releases (v64 = node10, see https://nodejs.org/en/download/releases/)

Bumped node engine to be v10

### CODE REVIEW

**Comment by vladgolubev** [comment]
Thanks for putting it together, Sam! 👍  I'll get it merged and published once you confirm it works

**Comment by samjeffress** [comment]
I've had a go at getting node 10 to work, but have got stuck at the test in https://github.com/samjeffress/aws-lambda-libreoffice/blob/node10/test.js#L10

I'm getting the error `/opt/instdir/program/oosplash: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory` - I'm not sure if it's because of brotli, or something that I'm doing. It's certainly unpacking a lot of things, but obviously not that shared library.

Any chance you could have a look @vladgolubev?

**Comment by vladgolubev** [comment]
FYI the nodejs10.x runtime is now using Node 10.16, which has native Brotli support.

See https://nodejs.org/docs/latest-v10.x/api/zlib.html#zlib_zlib_brotlidecompress_buffer_options_callback

**Comment by mrvisser** [comment]
@vladgolubev It looks like 10.16.3 at least doesn't have native brotli support. Oddly, that link suggests that it does, but latest docs say it was added in 11.7.0: https://nodejs.org/api/zlib.html#zlib_class_brotlioptions

When I get the `10.17.0` `@types/node`, it's not listed as an option, and trying to override it and run something like `zlib.brotliDecompress` from the 10.x lambda run time (which should be `10.16.3` as of now gives me the error: `zlib.brotliDecompress is not a function`

**Comment by vladgolubev** [comment]
@mrvisser strange, for me it says it was added in 10.16.0 
image

And it's certainly available in Lambda
image

**Comment by mrvisser** [comment]
@vladgolubev Thanks for the nudge. It's definitely there, I ran the 8.x lambda runtime which is why it said the function didn't exist. I was further confused by the latest docs saying it wasn't added until 11.7:

image

... and what seems to be a lack of support in `@types/node@10.17.0`.

**Comment by vladgolubev** [comment]
[v1.0.0](https://github.com/shelfio/aws-lambda-brotli-unpacker/releases/tag/v1.0.0) is published which supports Node 10.x & 12.x

AWS deprecates node 8, so I decided not to keep backward compatibility, as you won't be able to updated Node 8 lambdas in 1-2 months.

**Pull request closed without merging**
